image:
  pullPolicy: IfNotPresent
  repository: shawly/ps3netsrv
  tag: v1.9.0@sha256:c6e344b636a74e4f034a74ce766cd859071f5e46a14a0a2895ac819e66db2107
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    # runAsGroup: 0
    # runAsUser: 0
service:
  main:
    ports:
      main:
        port: 38008
        protocol: http
        targetPort: 38008
persistence:
  games:
    enabled: true
    mountPath: /games
  varrun:
    enabled: true
portal:
  open:
    enabled: true
